// IPC 通道名常量，供 main 与 preload 共享，避免字符串手误。
export const IPC = {
  treeGet: 'tree:get',
  treeChanged: 'tree:changed',
  projectAdd: 'project:add',
  projectAddByPath: 'project:add-by-path',
  projectRemove: 'project:remove',
  run: 'session:run',
  stop: 'session:stop',
  stdin: 'session:stdin',
  resize: 'session:resize',
  sessionBuffer: 'session:buffer',
  sessions: 'session:list',
  sessionOutput: 'session:output',
  sessionStatus: 'session:status',
  sessionRemoved: 'session:removed',
  terminalOpen: 'terminal:open',
  sessionClose: 'session:close',
  terminals: 'terminal:list',
  configCreate: 'config:create',
  configUpdate: 'config:update',
  configDelete: 'config:delete',
  configReorder: 'config:reorder',
  scriptPromote: 'script:promote',
  openExternal: 'shell:open-external',
  openPath: 'shell:open-path',
  gitLoad: 'git:load',
  gitDetails: 'git:details',
  gitFileDiff: 'git:file-diff',
  gitTagDetails: 'git:tag-details',
  gitRepoConfig: 'git:repo-config',
  gitAction: 'git:action',
  gitSettingsGet: 'git:settings-get',
  gitSettingsSet: 'git:settings-set',
  gitViewPrefsGet: 'git:view-prefs-get',
  gitViewPrefsSet: 'git:view-prefs-set',
  gitChanged: 'git:changed'
} as const
