// IPC 通道名常量，供 main 与 preload 共享，避免字符串手误。
export const IPC = {
  treeGet: 'tree:get',
  treeChanged: 'tree:changed',
  projectAdd: 'project:add',
  projectAddByPath: 'project:add-by-path',
  projectCreate: 'project:create',
  /** 从 Git 仓库克隆并登记：start 启动（进度经 progress 事件流式推送）、cancel 取消、
   * check-target 探测目标目录是否可用 */
  projectClone: 'project:clone',
  projectCloneCancel: 'project:clone-cancel',
  projectCloneCheckTarget: 'project:clone-check-target',
  projectCloneProgress: 'project:clone-progress',
  projectRemove: 'project:remove',
  projectReorder: 'project:reorder',
  projectTouch: 'project:touch',
  projectSetPinned: 'project:set-pinned',
  projectSortPrefsGet: 'project:sort-prefs-get',
  projectSortPrefsSet: 'project:sort-prefs-set',
  appPrefsGet: 'app:prefs-get',
  appPrefsSet: 'app:prefs-set',
  /** 主进程 → 全部窗口：应用偏好已变（任一窗口的设置弹窗改的） */
  appPrefsChanged: 'app:prefs-changed',
  /** 通用目录选择器（不绑定项目；克隆对话框选存放位置用） */
  pickDirectory: 'dialog:pick-directory',
  /** 读系统剪贴板纯文本（克隆对话框预填仓库地址用） */
  clipboardReadText: 'clipboard:read-text',
  windowsShellOptions: 'app:windows-shell-options',
  /** External Open：主进程登记项目后通知渲染端选中（携带 focusPath） */
  projectExternalOpen: 'project:external-open',
  /** Preview Window：上翻根（换授权与监听）/ 把当前根登记为项目并在主窗口选中 */
  previewSetRoot: 'preview:set-root',
  previewAddProject: 'preview:add-project',
  /** 主窗口项目菜单「在新窗口中打开」：以已登记项目根开一个 Preview Window */
  previewOpenRoot: 'preview:open-root',
  /** 系统集成（设置「系统集成」栏） */
  integrationGet: 'integration:get',
  integrationApply: 'integration:apply',
  run: 'session:run',
  stop: 'session:stop',
  stdin: 'session:stdin',
  resize: 'session:resize',
  sessionBuffer: 'session:buffer',
  sessionClear: 'session:clear',
  sessions: 'session:list',
  sessionOutput: 'session:output',
  sessionStatus: 'session:status',
  sessionRemoved: 'session:removed',
  terminalOpen: 'terminal:open',
  sessionClose: 'session:close',
  terminals: 'terminal:list',
  workspaceUiGet: 'workspace:ui-get',
  workspaceUiSet: 'workspace:ui-set',
  configCreate: 'config:create',
  configUpdate: 'config:update',
  configDelete: 'config:delete',
  configReorder: 'config:reorder',
  /** 为命令型配置挑选工作目录（返回相对项目根或绝对路径；取消为 null） */
  configPickCwd: 'config:pick-cwd',
  scriptPromote: 'script:promote',
  openExternal: 'shell:open-external',
  openPath: 'shell:open-path',
  openInFolder: 'shell:open-in-folder',
  openInAppList: 'shell:open-in-app-list',
  openInApp: 'shell:open-in-app',
  filesListDir: 'files:list-dir',
  filesFilterTree: 'files:filter-tree',
  filesRead: 'files:read',
  filesWrite: 'files:write',
  filesHeadText: 'files:head-text',
  /** 超大位图：预览图（先）与瓦片金字塔（后台生成，命中缓存即返回） */
  filesImagePreview: 'files:image-preview',
  filesImagePyramid: 'files:image-pyramid',
  filesCreate: 'files:create',
  filesRename: 'files:rename',
  filesTrash: 'files:trash',
  /** 「复制文件」：把文件 / 文件夹本身放进系统剪贴板（只放行授权根内路径） */
  filesCopyFile: 'files:copy-file',
  filesGetUi: 'files:ui-get',
  filesSetUi: 'files:ui-set',
  filesChanged: 'files:changed',
  /** 内容搜索（Content Search）：start 启动（自动替换进行中的搜索）、stop 终止、event 流式推送结果 */
  contentSearchStart: 'content-search:start',
  contentSearchStop: 'content-search:stop',
  contentSearchEvent: 'content-search:event',
  gitLoad: 'git:load',
  gitDetails: 'git:details',
  gitFileDiff: 'git:file-diff',
  gitFileImage: 'git:file-image',
  gitTagDetails: 'git:tag-details',
  gitRepoConfig: 'git:repo-config',
  gitAction: 'git:action',
  gitSettingsGet: 'git:settings-get',
  gitSettingsSet: 'git:settings-set',
  gitViewPrefsGet: 'git:view-prefs-get',
  gitViewPrefsSet: 'git:view-prefs-set',
  gitChanged: 'git:changed',
  gitRevalidate: 'git:revalidate',
  gitDefaultBranch: 'git:default-branch',
  /** 主进程 before-input-event 命中后下发的应用快捷键 */
  appShortcut: 'app:shortcut',
  /** preload 同步拉取首屏快照（须在 loadURL 前注册） */
  bootstrapSync: 'bootstrap:sync',
  /** 应用内更新 */
  appUpdateGet: 'app-update:get',
  appUpdateCheck: 'app-update:check',
  appUpdatePerform: 'app-update:perform',
  appUpdateOpenRelease: 'app-update:open-release',
  appUpdateState: 'app-update:state',
  /** 仅未包装开发：顶栏绿色按钮读工作区 CHANGELOG.md 做本地预览 */
  appUpdateDevPreview: 'app-update:dev-preview'
} as const
