// IPC 通道名常量，供 main 与 preload 共享，避免字符串手误。
export const IPC = {
  treeGet: 'tree:get',
  treeChanged: 'tree:changed',
  projectAdd: 'project:add',
  projectAddByPath: 'project:add-by-path',
  projectCreate: 'project:create',
  projectRemove: 'project:remove',
  projectReorder: 'project:reorder',
  projectTouch: 'project:touch',
  projectSetPinned: 'project:set-pinned',
  projectSortPrefsGet: 'project:sort-prefs-get',
  projectSortPrefsSet: 'project:sort-prefs-set',
  run: 'session:run',
  stop: 'session:stop',
  stdin: 'session:stdin',
  resize: 'session:resize',
  sessionBuffer: 'session:buffer',
  sessionClear: 'session:clear',
  sessions: 'session:list',
  sessionOutput: 'session:output',
  sessionStatus: 'session:status',
  sessionRemoved: 'session:removed',
  terminalOpen: 'terminal:open',
  sessionClose: 'session:close',
  terminals: 'terminal:list',
  workspaceUiGet: 'workspace:ui-get',
  workspaceUiSet: 'workspace:ui-set',
  configCreate: 'config:create',
  configUpdate: 'config:update',
  configDelete: 'config:delete',
  configReorder: 'config:reorder',
  scriptPromote: 'script:promote',
  openExternal: 'shell:open-external',
  openPath: 'shell:open-path',
  openInFolder: 'shell:open-in-folder',
  filesListDir: 'files:list-dir',
  filesFilterTree: 'files:filter-tree',
  filesRead: 'files:read',
  filesWrite: 'files:write',
  filesGetUi: 'files:ui-get',
  filesSetUi: 'files:ui-set',
  filesChanged: 'files:changed',
  gitLoad: 'git:load',
  gitDetails: 'git:details',
  gitFileDiff: 'git:file-diff',
  gitFileImage: 'git:file-image',
  gitTagDetails: 'git:tag-details',
  gitRepoConfig: 'git:repo-config',
  gitAction: 'git:action',
  gitSettingsGet: 'git:settings-get',
  gitSettingsSet: 'git:settings-set',
  gitViewPrefsGet: 'git:view-prefs-get',
  gitViewPrefsSet: 'git:view-prefs-set',
  gitChanged: 'git:changed',
  gitRevalidate: 'git:revalidate',
  gitDefaultBranch: 'git:default-branch',
  /** 主进程 before-input-event 命中后下发的应用快捷键 */
  appShortcut: 'app:shortcut',
  /** preload 同步拉取首屏快照（须在 loadURL 前注册） */
  bootstrapSync: 'bootstrap:sync',
  /** 应用内更新 */
  appUpdateGet: 'app-update:get',
  appUpdateCheck: 'app-update:check',
  appUpdatePerform: 'app-update:perform',
  appUpdateOpenRelease: 'app-update:open-release',
  appUpdateState: 'app-update:state'
} as const
